const SOURCE_CATALOG = [
  {
    key: "linkedin",
    name: "LinkedIn",
    market: "Global",
    category: "global",
    searchSupport: "Partner/manual import",
    shortlistSupport: "Supported after normalization",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "LinkedIn application flows are restricted and typically require a manual in-browser submit.",
    ingestMode: "partner",
    liveSearchImplemented: true,
    status: "active",
  },
  {
    key: "indeed",
    name: "Indeed",
    market: "Global",
    category: "global",
    searchSupport: "Adapter-ready",
    shortlistSupport: "Supported after normalization",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Indeed application flows vary by employer and need manual review before submission.",
    ingestMode: "adapter_ready",
    liveSearchImplemented: true,
    status: "active",
  },
  {
    key: "glassdoor",
    name: "Glassdoor",
    market: "Global",
    category: "global",
    searchSupport: "Adapter-ready",
    shortlistSupport: "Supported after normalization",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Glassdoor job flows typically redirect externally and should be treated as manual completion.",
    ingestMode: "adapter_ready",
    liveSearchImplemented: false,
    status: "planned",
  },
  {
    key: "wellfound",
    name: "Wellfound",
    market: "Global",
    category: "global",
    searchSupport: "Adapter-ready",
    shortlistSupport: "Supported",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Wellfound jobs should open in the original portal for manual completion.",
    ingestMode: "adapter_ready",
    liveSearchImplemented: true,
    status: "active",
  },
  {
    key: "remotive",
    name: "Remotive",
    market: "Global",
    category: "global",
    searchSupport: "Adapter-ready",
    shortlistSupport: "Supported",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Remotive listings commonly hand off to employer application pages, so final submission stays manual.",
    ingestMode: "adapter_ready",
    liveSearchImplemented: true,
    status: "active",
  },
  {
    key: "weworkremotely",
    name: "WeWorkRemotely",
    market: "Global",
    category: "global",
    searchSupport: "Adapter-ready",
    shortlistSupport: "Supported",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "WeWorkRemotely typically redirects to external employer flows, so manual completion is required.",
    ingestMode: "adapter_ready",
    liveSearchImplemented: true,
    status: "active",
  },
  {
    key: "remoteok",
    name: "RemoteOK",
    market: "Global",
    category: "global",
    searchSupport: "API/feed friendly",
    shortlistSupport: "Supported",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "RemoteOK listings open on the original employer workflow and should stay manual.",
    ingestMode: "api_live",
    liveSearchImplemented: true,
    status: "active",
  },
  {
    key: "greenhouse",
    name: "Greenhouse",
    market: "Global",
    category: "global",
    searchSupport: "API/feed friendly",
    shortlistSupport: "Supported",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Greenhouse jobs are excellent for search aggregation, but submission should remain manual unless a first-party apply integration exists.",
    ingestMode: "feed_ready",
    liveSearchImplemented: true,
    status: "active",
  },
  {
    key: "lever",
    name: "Lever",
    market: "Global",
    category: "global",
    searchSupport: "API/feed friendly",
    shortlistSupport: "Supported",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Lever is strong for job discovery, but safe production usage keeps the final apply step manual.",
    ingestMode: "feed_ready",
    liveSearchImplemented: false,
    status: "planned",
  },
  {
    key: "workday",
    name: "Workday",
    market: "Global",
    category: "global",
    searchSupport: "Adapter-ready",
    shortlistSupport: "Supported after normalization",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Workday apply flows are highly variable and should not be treated as universally automatable.",
    ingestMode: "adapter_ready",
    liveSearchImplemented: false,
    status: "planned",
  },
  {
    key: "naukri",
    name: "Naukri",
    market: "India",
    category: "india",
    searchSupport: "Adapter-ready",
    shortlistSupport: "Supported",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Naukri application flows require a manual completion step to stay reliable.",
    ingestMode: "adapter_ready",
    liveSearchImplemented: true,
    status: "active",
  },
  {
    key: "shine",
    name: "Shine",
    market: "India",
    category: "india",
    searchSupport: "Adapter-ready",
    shortlistSupport: "Supported after normalization",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Shine listings often redirect to external employer flows, so HireFlow should prepare assets and hand off manual completion.",
    ingestMode: "adapter_ready",
    liveSearchImplemented: false,
    status: "planned",
  },
  {
    key: "instahire",
    name: "Instahyre",
    market: "India",
    category: "india",
    searchSupport: "Adapter-ready",
    shortlistSupport: "Supported",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Instahyre flows can be semi-structured, but final submission should remain manual unless first-party integration exists.",
    ingestMode: "adapter_ready",
    liveSearchImplemented: false,
    status: "planned",
  },
  {
    key: "foundit",
    name: "Foundit",
    market: "India",
    category: "india",
    searchSupport: "Adapter-ready",
    shortlistSupport: "Supported after normalization",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Foundit application pages require manual review and completion to stay safe and reliable.",
    ingestMode: "adapter_ready",
    liveSearchImplemented: false,
    status: "planned",
  },
  {
    key: "iimjobs",
    name: "IIMJobs",
    market: "India",
    category: "india",
    searchSupport: "Adapter-ready",
    shortlistSupport: "Supported",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "IIMJobs can feed targeted roles into the queue, but final application steps should remain manual.",
    ingestMode: "adapter_ready",
    liveSearchImplemented: false,
    status: "planned",
  },
  {
    key: "angellistindia",
    name: "AngelList India",
    market: "India",
    category: "india",
    searchSupport: "Legacy/manual import",
    shortlistSupport: "Supported after normalization",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "AngelList India is best treated as a legacy/manual-import source rather than a guaranteed live feed.",
    ingestMode: "manual_import",
    liveSearchImplemented: false,
    status: "legacy",
  },
  {
    key: "cutshort",
    name: "Cutshort",
    market: "India",
    category: "india",
    searchSupport: "Adapter-ready",
    shortlistSupport: "Supported",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Cutshort can feed jobs into HireFlow, but direct application still needs a manual completion step.",
    ingestMode: "adapter_ready",
    liveSearchImplemented: false,
    status: "planned",
  },
  {
    key: "ycjobs",
    name: "YC Jobs",
    market: "Startup",
    category: "startup",
    searchSupport: "Portfolio/feed ready",
    shortlistSupport: "Supported",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "YC company roles can be aggregated safely, but application submission still belongs on the employer side.",
    ingestMode: "feed_ready",
    liveSearchImplemented: false,
    status: "planned",
  },
  {
    key: "a16zportfolio",
    name: "a16z Portfolio Jobs",
    market: "Startup",
    category: "startup",
    searchSupport: "Portfolio/feed ready",
    shortlistSupport: "Supported",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Portfolio job boards are ideal for aggregation, but HireFlow should hand off final employer applications manually.",
    ingestMode: "feed_ready",
    liveSearchImplemented: false,
    status: "planned",
  },
  {
    key: "sequoiaportfolio",
    name: "Sequoia Portfolio Jobs",
    market: "Startup",
    category: "startup",
    searchSupport: "Portfolio/feed ready",
    shortlistSupport: "Supported",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Portfolio job boards are strong aggregation targets, but final application should remain employer-side.",
    ingestMode: "feed_ready",
    liveSearchImplemented: false,
    status: "planned",
  },
  {
    key: "githubjobs",
    name: "GitHub Jobs",
    market: "Niche",
    category: "niche",
    searchSupport: "Not active",
    shortlistSupport: "Historical only",
    autoApplyLabel: "Unavailable",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "GitHub Jobs is no longer active, so HireFlow should not present it as a live source.",
    ingestMode: "inactive",
    liveSearchImplemented: false,
    status: "inactive",
  },
  {
    key: "stackoverflowjobs",
    name: "Stack Overflow Jobs",
    market: "Niche",
    category: "niche",
    searchSupport: "Not active",
    shortlistSupport: "Historical only",
    autoApplyLabel: "Unavailable",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Stack Overflow Jobs is no longer active, so it should be treated as a legacy reference only.",
    ingestMode: "inactive",
    liveSearchImplemented: false,
    status: "inactive",
  },
  {
    key: "hackernewshiring",
    name: "Hacker News Who's Hiring",
    market: "Niche",
    category: "niche",
    searchSupport: "Manual/community import",
    shortlistSupport: "Supported after normalization",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Hacker News hiring posts are community threads, so HireFlow should treat them as manual-import opportunities.",
    ingestMode: "manual_import",
    liveSearchImplemented: false,
    status: "planned",
  },
  {
    key: "adzuna",
    name: "Adzuna",
    market: "Global",
    category: "global",
    searchSupport: "API live",
    shortlistSupport: "Supported",
    autoApplyLabel: "Manual Apply",
    autoApplySupported: false,
    manualActionRequired: true,
    manualActionReason:
      "Adzuna results redirect to external application pages, so HireFlow prepares assets and hands off manual completion.",
    ingestMode: "api_live",
    liveSearchImplemented: true,
    status: "active",
  },
];

const SOURCE_LOOKUP = Object.fromEntries(SOURCE_CATALOG.map((item) => [item.key, item]));

const normalizeSourceKey = (source = "") =>
  String(source || "")
    .trim()
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/\+/g, "plus")
    .replace(/\s+/g, "")
    .replace(/[^a-z]/g, "");

const normalizeCatalogItem = (item) => ({
  key: item.key,
  source: item.name,
  name: item.name,
  market: item.market,
  category: item.category,
  searchSupport: item.searchSupport,
  shortlistSupport: item.shortlistSupport,
  autoApplyLabel: item.autoApplyLabel,
  autoApplySupported: item.autoApplySupported,
  manualActionRequired: item.manualActionRequired,
  manualActionReason: item.manualActionReason,
  ingestMode: item.ingestMode,
  liveSearchImplemented: item.liveSearchImplemented,
  status: item.status,
});

export const getJobSourceMetadata = (source = "") => {
  const normalized = normalizeSourceKey(source);
  const item = SOURCE_LOOKUP[normalized] || SOURCE_LOOKUP.adzuna;
  return normalizeCatalogItem(item);
};

export const getSupportedSourceCatalog = () =>
  SOURCE_CATALOG.map((item) => normalizeCatalogItem(item));

export const getSourceCatalogByCategory = () => ({
  india: getSupportedSourceCatalog().filter((item) => item.category === "india"),
  global: getSupportedSourceCatalog().filter((item) => item.category === "global"),
  startup: getSupportedSourceCatalog().filter((item) => item.category === "startup"),
  niche: getSupportedSourceCatalog().filter((item) => item.category === "niche"),
});
